version: 2.1

executors:
  default_container:
    docker:
      - image: circleci/ruby:2.6.1
        environment:
          RAILS_ENV: test
          MYSQL_HOST: 127.0.0.1
          MYSQL_USERNAME: 'root'
          MYSQL_PASSWORD: ''
          MYSQL_PORT: 3306
      - image: circleci/mysql:5.7-ram
        environment:
          MYSQL_DATABASE: circleci-example-for-rails_test
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_HOST: '%'
    working_directory: ~/circle-example-for-rails

jobs:
  fetch_source_code:
    executor:
      name: default_container
    steps:
      - checkout
      - save_cache:
          key: v4-circleci-example-for-rails-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/circle-example-for-rails

  bundle_dependencies:
    executor:
      name: default_container
    steps:
      - restore_cache: # ソースコードの復元
          key: v4-circleci-example-for-rails-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache: # vendor/bundleを復元
          key: v4-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Bundle Install Dependencies
          command: |
            gem install bundler -v 2.0.1
            bundle install
      - save_cache:
          key: v4-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  rspec:
    executor:
      name: default_container
    steps:
      - restore_cache: # ソースコードの復元
          key: v4-circleci-example-for-rails-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache: # vendor/bundleを復元
          key: v4-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Watting stand up database
          command: |
            dockerize -wait \
            tcp://127.0.0.1:3306 -timeout 120s

      # Database setup
      - run: rm ./config/database.yml
      - run: mv ./config/database.yml.ci ./config/database.yml
      - run:
          name: Testing DB migration and seed
          command: |
            bundle exec rails db:create db:migrate db:seed db:drop
      # run tests!
      - run:
          name: Run rspec
          command: |
            mkdir /tmp/test-results
            mkdir -p ~/rspec
            bundle exec rails db:create db:migrate
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            gem install bundler -v 2.0.1
            bundle exec rspec --require rails_helper \
                              --color \
                              --format progress \
                              --format RspecJunitFormatter \
                              --out ~/rspec/rspec.xml

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

workflows:
  build:
    jobs:
      - fetch_source_code
      - bundle_dependencies:
          requires:
            - fetch_source_code
      - rspec:
          requires: # bundle_dependenciesの後にrspecを実行する
            - bundle_dependencies
